Change default udev filtering rule as byname only
project-akri/akri-docs pull request #43
Opened 2022-08-12 06:59 UTC by leolumicrosoft

Move advanced filtering such as by device capacity or vendor to note

2022-08-12 17:00 UTC, kate-goldenring requested changes
Thank you @leolumicrosoft. Love the description in the note and the added tip on how to get the device capabilities. 
Once the capture capability is removed from the installation command (`helm install ...`) later in the doc, this should be good to go!

2022-08-12 17:24 UTC, bfjelds approved these changes

2022-08-15 03:13 UTC, leolumicrosoft commented
Helm installation script is updated. Note that "going beyond the demo" is not changed since that is assumed for experiment using real camera device.

2022-08-15 15:17 UTC, kate-goldenring approved these changes
Thanks for fixing this up!

2022-08-15 15:19 UTC, merged